from collections.abc import AsyncIterator
from typing import Protocol


class StorageBackend(Protocol):
    async def save(self, key: str, data: bytes) -> None: ...
    async def save_file(self, key: str, path: str) -> None: ...
    async def open_stream(self, key: str) -> AsyncIterator[bytes]: ...
    async def read_range(self, key: str, start: int, end: int | None) -> AsyncIterator[bytes]: ...
    async def get_size(self, key: str) -> int: ...
    async def delete(self, key: str) -> None: ...
    async def exists(self, key: str) -> bool: ...
